name: motivator_ai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
    
  # Core packages
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  uuid: ^4.1.0
  http: ^0.13.6
  path_provider: ^2.1.2
  
  # Audio and permissions
  just_audio: ^0.9.34
  permission_handler: ^11.0.1
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Speech input + scheduling
  speech_to_text: ^7.0.0
  flutter_datetime_picker_plus: ^2.0.1
  
  # 🔔 Notification dependencies
  awesome_notifications: ^0.10.1
  timezone: ^0.9.2
  
  # 🚨 AMBER ALERT DEPENDENCIES
  wakelock_plus: ^1.2.1               # Keep screen on during emergency alerts (updated package)
  
  # 🎤 DICTAPHONE DEPENDENCIES
  flutter_sound: ^9.2.13              # Audio recording (replaced record package)
  record: ^4.4.4
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/voices/premium/

dependency_overrides:
  awesome_notifications: ^0.10.1