name: motivator_ai
description: "MOTIVATR & Co - AI-Enhanced Personal Companions"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
    
  # ===== CORE PACKAGES (CURRENT WORKING) =====
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  path_provider: ^2.1.2
  
  # ===== AUDIO & PERMISSIONS (CURRENT WORKING) =====
  just_audio: ^0.9.34
  permission_handler: ^11.0.1
  
  # ===== CALENDAR (CURRENT WORKING) =====
  table_calendar: ^3.0.9
  
  # ===== SPEECH & SCHEDULING (CURRENT WORKING) =====
  speech_to_text: ^7.0.0
  flutter_datetime_picker_plus: ^2.0.1
  web_socket_channel: ^3.0.3 
  
  # ===== NOTIFICATIONS (CURRENT WORKING) =====
  awesome_notifications: ^0.10.1
  timezone: ^0.9.2
  wakelock_plus: ^1.2.1
  
  # ===== AUDIO SYSTEM (CURRENT WORKING) =====
  flutter_sound: ^9.2.13
  flutter_tts: ^4.2.3
  audioplayers: ^6.5.0
  
  # ===== BASIC NETWORKING =====
  http: ^0.13.6                      # Keep current version for stability

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  awesome_notifications: ^0.10.1

flutter:
  uses-material-design: true
  
  # ===== ENTERPRISE TYPOGRAPHY SYSTEM =====
  fonts:
    - family: Hanken Grotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/HankenGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/HankenGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/HankenGrotesk-Bold.ttf
          weight: 700
  
  assets:
    # ===== CORE ASSETS =====
    - assets/voices/premium/
    - assets/fonts/
    
    # ===== AUDIO LIBRARY (CURRENT WORKING) =====
    - assets/audio/backchannel/of_course_yeah.mp3
    - assets/audio/backchannel/Hey_you_GoodMorning.mp3
    - assets/audio/backchannel/damn_no_i_get_it.mp3
    - assets/audio/backchannel/mhmm_let_me_think.mp3
    - assets/audio/backchannel/mhmm_let_me_think_2.mp3
    - assets/audio/backchannel/oh_no_way.mp3
    - assets/audio/backchannel/happy_laugh_yearight.mp3
    - assets/audio/backchannel/laughs_yearight.mp3
    - assets/audio/backchannel/happy_birthday_no_sing.mp3
    - assets/audio/backchannel/Happy_Birthday_sing.mp3
    
    # ✅ ACKNOWLEDGMENT CLIPS
    - assets/audio/backchannel/stronger_Mmhmm_acknowledgement.mp3
    - assets/audio/backchannel/happy_Mmhmm_acknowledgement.mp3
    - assets/audio/backchannel/clearing_throat_choking_Mhmm.mp3
    - assets/audio/backchannel/Got_It_Acknowledge.mp3
    - assets/audio/backchannel/Lively_Right_Acknowledge.mp3
    - assets/audio/backchannel/Average_I_Get_It.mp3
    - assets/audio/backchannel/sarcastic_Mmhmm.mp3
    
    # 🧠 UNDERSTANDING & PROCESSING
    - assets/audio/backchannel/I_see_caring.mp3
    - assets/audio/backchannel/Average_That_Makes_Sense.mp3
    - assets/audio/backchannel/Average_Totally.mp3
    - assets/audio/backchannel/Average_Of_Course.mp3
    - assets/audio/backchannel/Average_For_Sure.mp3
    - assets/audio/backchannel/Average_Absolutely_Version_2.mp3
    
    # 🤔 CURIOSITY & QUESTIONS
    - assets/audio/backchannel/Curious_Really.mp3
    - assets/audio/backchannel/Oh_Wow.mp3
    - assets/audio/backchannel/Surprised_OOooh.mp3
    - assets/audio/backchannel/Very_Intrigued_Thats_a_Good_Question.mp3
    - assets/audio/backchannel/Seriously_Question.mp3
    - assets/audio/backchannel/No_Way.mp3
    - assets/audio/backchannel/Breathing_Whoa_No_Kidding.mp3
    - assets/audio/backchannel/I_Had_No_Idea.mp3
    
    # 🎯 AGREEMENT & CONFIRMATION
    - assets/audio/backchannel/Agreement_Exactly.mp3
    - assets/audio/backchannel/Totally_Agree.mp3
    - assets/audio/backchannel/Youre_Right.mp3
    - assets/audio/backchannel/100_Percent.mp3
    - assets/audio/backchannel/Definitely.mp3
    - assets/audio/backchannel/Upbeat_Absolutely.mp3
    
    # 🤯 THINKING & PROCESSING (Complex Topics)
    - assets/audio/backchannel/OH_Let_Me_Process_That.mp3
    - assets/audio/backchannel/Laughing_Let_Me_Think_About_That.mp3
    - assets/audio/backchannel/Breathing_Chuckle_Let_Me_Think_About_That.mp3
    - assets/audio/backchannel/Genuine_Laughing_While_Saying_Let_Me_Think_About_That.mp3
    - assets/audio/backchannel/Flirty_Laughing_Let_Me_Think_About_That_Thats_Good_Question.mp3
    - assets/audio/backchannel/filler_quick_hmm.mp3
    
    # 🎉 EXCITEMENT & POSITIVE REACTIONS
    - assets/audio/backchannel/excited_YEAH.mp3
    - assets/audio/backchannel/Thats_Amazing.mp3
    - assets/audio/backchannel/Thats_Wild.mp3
    - assets/audio/backchannel/Cool.mp3
    - assets/audio/backchannel/small_chuckle_yeah.mp3
    
    # 💙 EMPATHY & CARING
    - assets/audio/backchannel/That_Sucks.mp3
    - assets/audio/backchannel/Caring_Empathetic_Oh_Man.mp3
    - assets/audio/backchannel/Caring_I_Feel_You.mp3
    - assets/audio/backchannel/Caring_I_Understand.mp3
    - assets/audio/backchannel/Caring_Thats_Tough.mp3
    
    # 🔄 FILLER TRANSITIONS (Natural Flow)
    - assets/audio/backchannel/Filler_Soo.mp3
    - assets/audio/backchannel/Filler_The_Way_I_See_It.mp3
    - assets/audio/backchannel/Filler_Wellll.mp3
    - assets/audio/backchannel/Filler_Yeah_Well.mp3
    - assets/audio/backchannel/Filler_Actually.mp3
    - assets/audio/backchannel/Filler_I_Mean.mp3
    - assets/audio/backchannel/Filer_Heres_The_Thing.mp3
    - assets/audio/backchannel/Filler_Mmm_Okay.mp3
    - assets/audio/backchannel/Filler_Huh_Lets_See.mp3
    - assets/audio/backchannel/Filler_Slightly_Annoyed_Yea_Well.mp3
    
    # 🎭 PLAYFUL & PERSONALITY
    - assets/audio/backchannel/Filler_Playful_Mmmm.mp3
    - assets/audio/backchannel/Sensual_Moan_Explicit.mp3